### ISSUE TITLE
Races data has "discipline" data_type

### ISSUE THREAD

**Issue by sedside** [MalekaiProject/malekaiAPI#9]
Subj :)

**Comment by MichaelFedora** [comment]
That it does; in some of Crowfall's live streams and/or news releases they state that Race attributes are internally the same as disciplines, so we followed suite and made them use the same data model.

If you need to check if something is a race, make sure the `data_type` is `discipline` and `type` is `race`. Otherwise the REST routes and GraphQL still treat races differently to be "backwards compatible" iirc
